/*********************************************************
* file name: patel_3_2.cpp
* programmer name: Shiv Patel
* date created: 9/19/20
* date of last revision: 9/19/20
* details of the revision: Ticket sales and income generated
* short description: There are three seating categories at a stadium. For a softball game, Class A seats cost $15,
                    Class B seats cost $12, and Class C seats cost $9.
                   Write a program that asks how many tickets for each class of seats were sold,
                    then displays the amount of income generated
                   from ticket sales. Format your dollar amount
                   in fixed-point notation, with two decimal places of precision, and
                    be sure the decimal point is always displayed.
**********************************************************/
#include <iostream>
#include <iomanip>
#include <cmath>
using namespace std;

int main()
{
    // Program description
    cout << "\n\nThis program will calculate and display" <<endl
         << "the amount of tickets sold for each seat class then it will \n"
            "display the amount of income generated from the ticket sales. \n\n";

    // Variables
    const float ClassASeat = 15.00, ClassBSeat = 12.00, ClassCSeat =  9.00;
    int seatsSoldA, seatsSoldB, seatsSoldC;
    float totalA, totalB,totalC ,totalincome;


    // Ask user for num of seats sold in each class (A,B,C)
    cout << "How many Class A seats were sold? : ";
    cin >> seatsSoldA;

    cout << "How many Class B seats were sold? : ";
    cin >> seatsSoldB;

    cout << "How many Class C seats were sold? : ";
    cin >> seatsSoldC;

    // Calculations
    totalA = seatsSoldA*ClassASeat;
    totalB = seatsSoldB*ClassBSeat;
    totalC = seatsSoldC*ClassCSeat;

    totalincome = totalA+totalB+totalC;

    // Display results
    cout << endl;
    cout << setprecision(2) << fixed;

    cout << "There were " << seatsSoldA << " Class A seats sold priced at $";
    cout << setw(6) << ClassASeat;
    cout << " which = $" << totalA << endl;

    cout << "There were " << seatsSoldB << " Class B seats sold priced at $";
    cout << setw(6) << ClassBSeat;
    cout << " which = $" << totalB << endl;

    cout << "There were " << seatsSoldC << " Class C seats sold priced at $";
    cout << setw(6) << ClassBSeat;
    cout << " which = $" << totalC << endl;

    cout << "The total income generated by from tickets sales = $"<<totalincome;

    return 0;
}

/***********************************

"/Users/shiv0248/Desktop/cmpsc 121/untitled12/cmake-build-debug/untitled12"

This program will calculate and display
the amount of tickets sold for each seat class then it will
display the amount of income generated from the ticket sales.

How many Class A seats were sold? : 5
How many Class B seats were sold? : 5
How many Class C seats were sold? : 5

There were 5 Class A seats sold priced at $ 15.00 which = $75.00
There were 5 Class B seats sold priced at $ 12.00 which = $60.00
There were 5 Class C seats sold priced at $ 12.00 which = $45.00
The total income generated by from tickets sales = $180.00
Process finished with exit code 0

**********************************/